name: flutter_mcp_ui_core
description: Core models, constants, and utilities for Flutter MCP UI system. Shared foundation for renderer and generator packages.
version: 0.1.0
homepage: https://github.com/app-appplayer/flutter_mcp_ui_core
repository: https://github.com/app-appplayer/flutter_mcp_ui_core
documentation: https://pub.dev/documentation/flutter_mcp_ui_core/latest/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0

topics:
  - ui
  - json
  - mcp
  - flutter
  - widgets